database:
  url: jdbc:mariadb://localhost:3306/es

spring:
  datasource:
    url: ${database.url}?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select 1
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    stream:
      bindings:
        attachmentEntity-out-0: # 첨부파일 entity 정보 업데이트 하기 위한 이벤트
          destination: attachment-entity.topic # queue name
          group: attachment
